name: Android CI

on:
  pull_request:
    branches: 
      - master
       
      
  push:
    branches: 
      - master
      - develop 
    
    
jobs:

  lint:
    name: Run Lint Analyzer tool
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Lint tool
      run: ./gradlew lint
    - name: lint-tool-results
      uses: actions/upload-artifact@v1
      with:
        name: lint-tool-results
        path: app/build/reports/lint-results.html
  
  
  checkstyle:
    name: Run Checkstyle tool
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Checkstyle tool
      run: ./gradlew checkstyle
    - name: Checkstyle results
      uses: actions/upload-artifact@v1
      with:
        name: checkstyle-tool-results
        path: app/build/reports/checkstyle/ 
  
  
  javadoc:
    name: Run Javadoc tool
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Javadoc tool
      run: ./gradlew generateJavadoc
    - name: JavaDoc results
      uses: actions/upload-artifact@v1
      with:
        name: javadoc-tool-results
        path: app/build/docs/javadoc/
   
  test:
     name: Run Test Cases
     runs-on: windows-latest

     steps:
     - uses: actions/checkout@v2
     - name: set up JDK 1.8
       uses: actions/setup-java@v1
       with:
        java-version: 1.8
     - name: Build with Test Cases
       run: ./gradlew test
     
   
   
   
  build:
    name: Build Project
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
