name: AndroidLint

on:
  push:
    paths:
      - .github/workflows/android-lint.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*

jobs:
  android_lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew lint
      - uses: yaab5825/AndroidProject@v1.0.2
        with:
          xml_path: build/reports/lint-results.xml
