name: Android CI

on:
  pull_request:
    branches: 
      - master
       
      
  push:
    branches: 
      - master
      - develop 
    
    
jobs:

  lint:
    name: Run Lint tool
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Lint tool
      run: ./gradlew lint
    - name: Unit tests results
      uses: actions/upload-artifact@v1
      with:
        name: lint-tool-results
        path: app/build/reports/lint-results.html
    
  javadoc:
    name: Run javadoc tool
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Javadoc tool
      run: ./gradlew generateJavadoc
    - name: JavaDoc results
      uses: actions/upload-artifact@v1
      with:
        name: javadoc-tool-results
        path: app/build/generated/javadoc/
   
  test:
     name: Run Test Cases
     runs-on: windows-latest

     steps:
     - uses: actions/checkout@v2
     - name: set up JDK 1.8
       uses: actions/setup-java@v1
       with:
        java-version: 1.8
     - name: Build with Test Cases
       run: ./gradlew test
     - name: Test results
       uses: actions/upload-artifact@v1
       with:
        name: test-cases-results
        path: app/build/reports/tests/testDebugUnitTest/index.html
   
   
   
  build:
    name: Build Project
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
