name: Android CI

on:
  pull_request:
    branches: 
      - master
       
      
  push:
    branches: 
      - master
      - develop 
    
    
jobs:
  test:
    name: Run Test Cases and upload result in file
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew test
    - name: Unit tests results
      uses: actions/upload-artifact@v1
      with:
        name: unit-tests-results
        path: app/build/reports/tests/testDebugUnitTest/index.html


  lint:
    name: Run Lint tool and upload result in file
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew lint
    - name: Unit tests results
      uses: actions/upload-artifact@v1
      with:
        name: lint-tool-results
        path: app/build/reports/lint-results.html
      
  build:
    name: Build Project
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
