name: Deploy & Generate APK

on:
  pull_request:
    branches: 
      - master
       
      
  push:
    branches: 
      - master
      - develop 
    
    
jobs:
  build:
    name: Build Project
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build

  apk:
    name: Deploy & Generate APK
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Generate APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
